const UI = {
  fr: {
    administration: 'Administration', databases: 'Bases de données', unification: 'Unification', selection: 'Sélection', errors: 'Erreurs', mappings: 'Correspondances', materialsProducts: 'Matériaux / produits', materials: 'Matériaux', products: 'Produits', componentEditing: 'Correction composants', customTools: 'Composants', search: 'Rechercher', all: 'Tous', selectedOnly: 'Sélectionnés uniquement', missingOnly: 'Sans correspondance uniquement', saveVersion: 'Enregistrer une nouvelle version', edit: 'Modifier', createCopy: 'Créer une copie', cancel: 'Annuler', newMaterial: 'Nouveau matériau', newProduct: 'Nouveau produit', saveNewMaterial: 'Enregistrer nouveau matériau', saveNewProduct: 'Enregistrer nouveau produit', saveChanges: 'Enregistrer les modifications', name: 'Nom', targetSearch: 'Rechercher un matériau ou produit TBZ', noResult: 'Aucun résultat', originalLignum: 'Original Lignum', correctedTbz: 'Valeur TBZ corrigée', changed: 'modifié', select: 'Sélection', serialNo: 'serialNo', id: 'id', interfaceLanguage: 'Langue de l’interface', translations: 'Traductions', material: 'matériau', product: 'produit', components: 'composants', ascending: 'croissant', descending: 'décroissant', unmapped: 'À faire correspondre', saveMappings: 'Enregistrer les correspondances', mappingIntro: 'Recherchez une cible par id, nom ou KBOB. Les valeurs TBZ différentes de l’original Lignum sont affichées en rouge.', selectionIntro: 'Choisissez les composants exposés dans l’application générale.', selectionTitle: 'Sélection principale Lignum', count: 'résultats', workingtitle: 'Titre de travail', languageFallback: 'Une valeur absente utilise automatiquement une traduction disponible.',
  },
  de: {
    administration: 'Verwaltung', databases: 'Datenbanken', unification: 'Vereinheitlichung', selection: 'Auswahl', errors: 'Fehler', mappings: 'Zuordnungen', materialsProducts: 'Materialien / Produkte', materials: 'Materialien', products: 'Produkte', componentEditing: 'Bauteile bearbeiten', customTools: 'Custom-Werkzeuge', search: 'Suchen', all: 'Alle', selectedOnly: 'Nur ausgewählte', missingOnly: 'Nur ohne Zuordnung', saveVersion: 'Neue Version speichern', edit: 'Bearbeiten', createCopy: 'Kopie erstellen', cancel: 'Abbrechen', newMaterial: 'Neues Material', newProduct: 'Neues Produkt', saveNewMaterial: 'Neues Material speichern', saveNewProduct: 'Neues Produkt speichern', saveChanges: 'Änderungen speichern', name: 'Name', targetSearch: 'TBZ-Material oder -Produkt suchen', noResult: 'Kein Ergebnis', originalLignum: 'Lignum-Original', correctedTbz: 'Korrigierter TBZ-Wert', changed: 'geändert', select: 'Auswahl', serialNo: 'Seriennummer', id: 'ID', interfaceLanguage: 'Sprache der Benutzeroberfläche', translations: 'Übersetzungen', material: 'Material', product: 'Produkt', components: 'Bauteile', ascending: 'aufsteigend', descending: 'absteigend', unmapped: 'Noch zuzuordnen', saveMappings: 'Zuordnungen speichern', mappingIntro: 'Ziel nach ID, Name oder KBOB suchen. Vom Lignum-Original abweichende TBZ-Werte werden rot angezeigt.', selectionIntro: 'Bauteile auswählen, die in der Hauptanwendung verfügbar sind.', selectionTitle: 'Lignum-Hauptauswahl', count: 'Ergebnisse', workingtitle: 'Arbeitstitel', languageFallback: 'Bei fehlendem Wert wird automatisch eine verfügbare Übersetzung verwendet.',
  },
  en: {
    administration: 'Administration', databases: 'Databases', unification: 'Unification', selection: 'Selection', errors: 'Errors', mappings: 'Mappings', materialsProducts: 'Materials / products', materials: 'Materials', products: 'Products', componentEditing: 'Edit components', customTools: 'Custom tools', search: 'Search', all: 'All', selectedOnly: 'Selected only', missingOnly: 'Unmapped only', saveVersion: 'Save a new version', edit: 'Edit', createCopy: 'Create a copy', cancel: 'Cancel', newMaterial: 'New material', newProduct: 'New product', saveNewMaterial: 'Save new material', saveNewProduct: 'Save new product', saveChanges: 'Save changes', name: 'Name', targetSearch: 'Search for a TBZ material or product', noResult: 'No result', originalLignum: 'Original Lignum', correctedTbz: 'Corrected TBZ value', changed: 'changed', select: 'Select', serialNo: 'serialNo', id: 'id', interfaceLanguage: 'Interface language', translations: 'Translations', material: 'material', product: 'product', components: 'components', ascending: 'ascending', descending: 'descending', unmapped: 'Mapping required', saveMappings: 'Save mappings', mappingIntro: 'Search by id, name or KBOB. TBZ values differing from the original Lignum value are shown in red.', selectionIntro: 'Choose the components exposed in the main application.', selectionTitle: 'Main Lignum selection', count: 'results', workingtitle: 'Working title', languageFallback: 'A missing value automatically falls back to an available translation.',
  },
};

UI.fr.customTools = 'Composants';
UI.de.customTools = 'Bauteile';
UI.en.customTools = 'Components';

Object.assign(UI.fr, {
  unifyTitle: 'Unifier les composants Lignum', unifyIntro: 'Fusionne les sources allemande, anglaise et française par id, reconstruit les traductions et les couches, puis versionne components_unified.json.', currentComponents: 'composants actuels', archivedVersions: 'versions archivées', unifyButton: 'Unifier les trois bases Lignum', unifying: 'Unification…', sourcesUsed: 'Sources utilisées', latestVersions: 'Dernières versions', diagnosticsTitle: 'Contrôle d’intégrité', diagnosticsIntro: 'Les références sont vérifiées contre les matériaux et produits TBZ actifs.', selectedDatabase: 'Base sélectionnée', unifiedDatabase: 'Base unifiée', warnings: 'avertissements', unresolvedIds: 'ids sans correspondance', generalIssues: 'Incohérences générales', unresolvedReferences: 'Références de couches non résolues', allReferencesResolved: 'Toutes les références correspondent à un matériau ou produit TBZ.', occurrences: 'occurrence(s)', layer: 'couche', componentCorrectionTitle: 'Corriger la base unifiée', componentJson: 'Composant JSON', componentJsonIntro: 'Cette vue conserve tous les champs imbriqués et permet une correction précise. L’id est verrouillé.',
});
Object.assign(UI.fr, { missingMapping: 'Aucune correspondance Lignum → TBZ', invalidMappingTarget: 'La cible TBZ n’existe pas dans les matériaux ou produits', unknownReference: 'Référence inconnue', mappedTo: 'cible TBZ' });
Object.assign(UI.de, {
  unifyTitle: 'Lignum-Bauteile vereinheitlichen', unifyIntro: 'Führt die deutschen, englischen und französischen Quellen über die ID zusammen, erstellt Übersetzungen und Schichten neu und versioniert components_unified.json.', currentComponents: 'aktuelle Bauteile', archivedVersions: 'archivierte Versionen', unifyButton: 'Drei Lignum-Datenbanken vereinheitlichen', unifying: 'Vereinheitlichung…', sourcesUsed: 'Verwendete Quellen', latestVersions: 'Letzte Versionen', diagnosticsTitle: 'Integritätsprüfung', diagnosticsIntro: 'Referenzen werden gegen die aktiven TBZ-Materialien und -Produkte geprüft.', selectedDatabase: 'Ausgewählte Datenbank', unifiedDatabase: 'Vereinheitlichte Datenbank', warnings: 'Warnungen', unresolvedIds: 'IDs ohne Zuordnung', generalIssues: 'Allgemeine Inkonsistenzen', unresolvedReferences: 'Nicht aufgelöste Schichtreferenzen', allReferencesResolved: 'Alle Referenzen entsprechen einem TBZ-Material oder -Produkt.', occurrences: 'Vorkommen', layer: 'Schicht', componentCorrectionTitle: 'Vereinheitlichte Datenbank korrigieren', componentJson: 'Bauteil-JSON', componentJsonIntro: 'Diese Ansicht erhält alle verschachtelten Felder und ermöglicht präzise Korrekturen. Die ID ist gesperrt.',
});
Object.assign(UI.de, { missingMapping: 'Keine Lignum → TBZ-Zuordnung', invalidMappingTarget: 'Das TBZ-Ziel existiert nicht in Materialien oder Produkten', unknownReference: 'Unbekannte Referenz', mappedTo: 'TBZ-Ziel' });
Object.assign(UI.en, {
  unifyTitle: 'Unify Lignum components', unifyIntro: 'Merges the German, English and French sources by id, rebuilds translations and layers, then versions components_unified.json.', currentComponents: 'current components', archivedVersions: 'archived versions', unifyButton: 'Unify the three Lignum databases', unifying: 'Unifying…', sourcesUsed: 'Sources used', latestVersions: 'Latest versions', diagnosticsTitle: 'Integrity check', diagnosticsIntro: 'References are checked against the active TBZ materials and products.', selectedDatabase: 'Selected database', unifiedDatabase: 'Unified database', warnings: 'warnings', unresolvedIds: 'unmapped ids', generalIssues: 'General inconsistencies', unresolvedReferences: 'Unresolved layer references', allReferencesResolved: 'All references match a TBZ material or product.', occurrences: 'occurrence(s)', layer: 'layer', componentCorrectionTitle: 'Correct the unified database', componentJson: 'Component JSON', componentJsonIntro: 'This view preserves every nested field and enables precise corrections. The id is locked.',
});
Object.assign(UI.en, { missingMapping: 'No Lignum → TBZ mapping', invalidMappingTarget: 'The TBZ target does not exist in materials or products', unknownReference: 'Unknown reference', mappedTo: 'TBZ target' });

Object.assign(UI.fr, { incompleteComponents: 'Composants incomplets' });
Object.assign(UI.de, { incompleteComponents: 'Unvollständige Bauteile' });
Object.assign(UI.en, { incompleteComponents: 'Incomplete components' });
Object.assign(UI.fr, { taxonomyManagement: 'Catégories' });
Object.assign(UI.de, { taxonomyManagement: 'Kategorien' });
Object.assign(UI.en, { taxonomyManagement: 'Categories' });
Object.assign(UI.fr, { userManagement: 'Utilisateurs' });
Object.assign(UI.de, { userManagement: 'Benutzer' });
Object.assign(UI.en, { userManagement: 'Users' });

UI.it = {
  ...UI.en,
  administration: 'Amministrazione', databases: 'Banche dati', selection: 'Selezione', errors: 'Errori', mappings: 'Corrispondenze', materialsProducts: 'Materiali / prodotti', incompleteComponents: 'Componenti incompleti', taxonomyManagement: 'Categorie', userManagement: 'Utenti', search: 'Cercare', edit: 'Modificare', newMaterial: 'Nuovo materiale', newProduct: 'Nuovo prodotto', saveChanges: 'Salva modifiche', translations: 'Traduzioni', unmapped: 'Da associare',
};

export const dashboardText = (lang) => UI[lang] || UI.fr;

const FIELD_LABELS = {
  fr: { id: 'Identifiant', workingtitle: 'Nom', materialTypeId: 'Type de matériau', materialcategoryId: 'Catégorie de matériau', productTypeId: 'Type de produit', productCategoryId: 'Catégorie de produit', functionId: 'Fonction', kbobId: 'Identifiant KBOB', siaId: 'Identifiant SIA', density_kg_m3: 'Masse volumique (kg/m³)', thickness_mm: 'Épaisseur (mm)', thermalConductivity_W_mK: 'Conductivité thermique (W/mK)', specificHeat_Wh_kgK: 'Chaleur spécifique (Wh/kgK)', specificHeat_J_kgK: 'Chaleur spécifique (J/kgK)', waterVaporDiffusionResistanceCoefficientDry: 'Résistance vapeur, sec', waterVaporDiffusionResistanceCoefficientWet: 'Résistance vapeur, humide', fireClassification: 'Classement au feu', reactionToFire: 'Réaction au feu', unit: 'Unité' },
  de: { id: 'Kennung', workingtitle: 'Name', materialTypeId: 'Materialtyp', materialcategoryId: 'Materialkategorie', productTypeId: 'Produkttyp', productCategoryId: 'Produktkategorie', functionId: 'Funktion', kbobId: 'KBOB-Kennung', siaId: 'SIA-Kennung', density_kg_m3: 'Dichte (kg/m³)', thickness_mm: 'Dicke (mm)', thermalConductivity_W_mK: 'Wärmeleitfähigkeit (W/mK)', specificHeat_Wh_kgK: 'Spezifische Wärme (Wh/kgK)', specificHeat_J_kgK: 'Spezifische Wärme (J/kgK)', waterVaporDiffusionResistanceCoefficientDry: 'Dampfdiffusionswiderstand, trocken', waterVaporDiffusionResistanceCoefficientWet: 'Dampfdiffusionswiderstand, feucht', fireClassification: 'Brandklassifizierung', reactionToFire: 'Brandverhalten', unit: 'Einheit' },
  en: { id: 'Identifier', workingtitle: 'Name', materialTypeId: 'Material type', materialcategoryId: 'Material category', productTypeId: 'Product type', productCategoryId: 'Product category', functionId: 'Function', kbobId: 'KBOB identifier', siaId: 'SIA identifier', density_kg_m3: 'Density (kg/m³)', thickness_mm: 'Thickness (mm)', thermalConductivity_W_mK: 'Thermal conductivity (W/mK)', specificHeat_Wh_kgK: 'Specific heat (Wh/kgK)', specificHeat_J_kgK: 'Specific heat (J/kgK)', waterVaporDiffusionResistanceCoefficientDry: 'Vapour resistance, dry', waterVaporDiffusionResistanceCoefficientWet: 'Vapour resistance, wet', fireClassification: 'Fire classification', reactionToFire: 'Reaction to fire', unit: 'Unit' },
};

export const dashboardFieldLabel = (key, lang) => (FIELD_LABELS[lang] || FIELD_LABELS.en)[key] || key;

export const localizedField = (item, lang, field = 'name') => {
  const translations = item?.translations || {};
  const order = [lang, 'fr', 'de', 'en', 'it'].filter((value, index, all) => value && all.indexOf(value) === index);
  for (const code of order) {
    const value = translations?.[code]?.[field];
    if (value !== null && value !== undefined && String(value).trim()) return value;
  }
  return field === 'name' ? item?.workingtitle || item?.serialNo || item?.id || '' : '';
};

export const localizedName = (item, lang) => localizedField(item, lang, 'name');
